feat: Bytes Store (#288)
<!--- Please provide a general summary of your changes in the title
above -->
Add `Store` implementation for the `Bytes` type to allow using `Bytes`
in contract storage. Also added test cases.

## Pull Request type

<!-- Please try to limit your pull request to one type; submit multiple
pull requests if needed. -->

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

<!-- Please describe the current behavior that you are modifying, or
link to a relevant issue. -->
Currently, when trying to use `Bytes` in contract storage you get errors
like this :
```
starknet::Store::<Bytes>::write(
                          ^***^
Error: Failed to compile test artifact, for detailed information go through the logs above
```

Issue Number: N/A

## What is the new behavior?

<!-- Please describe the behavior or changes that are being added by
this PR. -->

- Add storage functions to allow using `Bytes` in storage
- `Bytes` stored in the following format :
- Only the size in bytes is stored in the original address where the
`Bytes` object is stored.
- The actual data is stored in chunks of 256 `u128` values in another
location in storage determined by the hash of:
    - The address storing the size of the bytes object.
    - The chunk index.
    - The short string "Bytes"

I used a very similar implementation to the `ByteArray` storage
functions from
[cairo/corelib](https://github.com/starkware-libs/cairo/blob/d090fec472ee3fc40f04b1a19bc362e7bb18e219/corelib/src/starknet/storage_access.cairo#L677)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

<!-- If this does introduce a breaking change, please describe the
impact and migration path for existing applications below. -->

## Other information

<!-- Any other information that is important to this PR, such as
screenshots of how the component looks before and after the change. -->

This would be useful since it is a common pattern in smart contract
programming to use storage for accessing values between requests/calls
and callbacks.

For example, this would help a lot in implementing `succinct-starknet`,
where a `Bytes` output is [passed to a callback through
storage](https://github.com/succinctlabs/succinctx/blob/9df6a9db651507d60ffa2d75eda3fe526d13f90a/contracts/src/SuccinctGateway.sol#L272).